version: "3"
services:
  web:
    build: .
#    deploy:
#      replicas: 5
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: 50M
#      restart_policy:
#        condition: on-failure
    volumes:
      - .:/usr/app
    command: npm start
    ports:
      - "80:8080"
    networks:
      - webnet
#    depends_on:
#      - mongodb
    env_file: .env

#  mongodb:
#    image: mvertes/alpine-mongo
#    ports:
#      - "27017:27017"

networks:
  webnet:
